cityflow:
  plan: [5, 30, 30, 30, 30, 30, 30, 30, 30]
  # phase_sequence: [1, 0, 3, 0, 2, 0, 4, 0]  # 0 is a common yellow phase
  roadnet_file: roadnet_16_3.json
  flow_file: anon_16_3_newyork_real.json
  roadnet_log_file: "frontend/web/roadnet_log_file.json"
  replay_log_file: "frontend/web/replay_log_file.txt"
  save_replay: False
  flow_rate_type: "random"
  flow_files: [
    "randomized/high/0__manhattan_16x3__gaussian_flows.json",
    "randomized/high/1__manhattan_16x3__gaussian_flows.json",
    "randomized/high/2__manhattan_16x3__gaussian_flows.json",
    "randomized/high/3__manhattan_16x3__gaussian_flows.json",
    "randomized/high/4__manhattan_16x3__gaussian_flows.json",
    "randomized/high/5__manhattan_16x3__gaussian_flows.json",
    "randomized/high/6__manhattan_16x3__gaussian_flows.json",
    "randomized/high/7__manhattan_16x3__gaussian_flows.json",
    "randomized/high/8__manhattan_16x3__gaussian_flows.json",
    "randomized/high/9__manhattan_16x3__gaussian_flows.json",
    "randomized/high/10__manhattan_16x3__gaussian_flows.json",
    "randomized/high/11__manhattan_16x3__gaussian_flows.json",
    "randomized/high/12__manhattan_16x3__gaussian_flows.json",
    "randomized/high/13__manhattan_16x3__gaussian_flows.json",
    "randomized/high/14__manhattan_16x3__gaussian_flows.json",
    "randomized/high/15__manhattan_16x3__gaussian_flows.json",
    "randomized/high/16__manhattan_16x3__gaussian_flows.json",
    "randomized/high/17__manhattan_16x3__gaussian_flows.json",
    "randomized/high/18__manhattan_16x3__gaussian_flows.json",
    "randomized/high/19__manhattan_16x3__gaussian_flows.json",
    "randomized/high/20__manhattan_16x3__gaussian_flows.json",
    "randomized/high/21__manhattan_16x3__gaussian_flows.json",
    "randomized/high/22__manhattan_16x3__gaussian_flows.json",
    "randomized/high/23__manhattan_16x3__gaussian_flows.json",
    "randomized/high/24__manhattan_16x3__gaussian_flows.json",
    "randomized/high/25__manhattan_16x3__gaussian_flows.json",
    "randomized/high/26__manhattan_16x3__gaussian_flows.json",
    "randomized/high/27__manhattan_16x3__gaussian_flows.json",
    "randomized/high/28__manhattan_16x3__gaussian_flows.json",
    "randomized/high/29__manhattan_16x3__gaussian_flows.json",
    "randomized/high/30__manhattan_16x3__gaussian_flows.json",
    "randomized/high/31__manhattan_16x3__gaussian_flows.json",
    "randomized/high/32__manhattan_16x3__gaussian_flows.json",
    "randomized/high/33__manhattan_16x3__gaussian_flows.json",
    "randomized/high/34__manhattan_16x3__gaussian_flows.json",
    "randomized/high/35__manhattan_16x3__gaussian_flows.json",
    "randomized/high/36__manhattan_16x3__gaussian_flows.json",
    "randomized/high/37__manhattan_16x3__gaussian_flows.json",
    "randomized/high/38__manhattan_16x3__gaussian_flows.json",
    "randomized/high/39__manhattan_16x3__gaussian_flows.json",
    "randomized/high/40__manhattan_16x3__gaussian_flows.json",
    "randomized/high/41__manhattan_16x3__gaussian_flows.json",
    "randomized/high/42__manhattan_16x3__gaussian_flows.json",
    "randomized/high/43__manhattan_16x3__gaussian_flows.json",
    "randomized/high/44__manhattan_16x3__gaussian_flows.json",
    "randomized/high/45__manhattan_16x3__gaussian_flows.json",
    "randomized/high/46__manhattan_16x3__gaussian_flows.json",
    "randomized/high/47__manhattan_16x3__gaussian_flows.json",
    "randomized/high/48__manhattan_16x3__gaussian_flows.json",
    "randomized/high/49__manhattan_16x3__gaussian_flows.json",
    "randomized/high/50__manhattan_16x3__gaussian_flows.json",
    "randomized/high/51__manhattan_16x3__gaussian_flows.json",
    "randomized/high/52__manhattan_16x3__gaussian_flows.json",
    "randomized/high/53__manhattan_16x3__gaussian_flows.json",
    "randomized/high/54__manhattan_16x3__gaussian_flows.json",
    "randomized/high/55__manhattan_16x3__gaussian_flows.json",
    "randomized/high/56__manhattan_16x3__gaussian_flows.json",
    "randomized/high/57__manhattan_16x3__gaussian_flows.json",
    "randomized/high/58__manhattan_16x3__gaussian_flows.json",
    "randomized/high/59__manhattan_16x3__gaussian_flows.json",
    "randomized/high/60__manhattan_16x3__gaussian_flows.json",
    "randomized/high/61__manhattan_16x3__gaussian_flows.json",
    "randomized/high/62__manhattan_16x3__gaussian_flows.json",
    "randomized/high/63__manhattan_16x3__gaussian_flows.json",
    "randomized/high/64__manhattan_16x3__gaussian_flows.json",
    "randomized/high/65__manhattan_16x3__gaussian_flows.json",
    "randomized/high/66__manhattan_16x3__gaussian_flows.json",
    "randomized/high/67__manhattan_16x3__gaussian_flows.json",
    "randomized/high/68__manhattan_16x3__gaussian_flows.json",
    "randomized/high/69__manhattan_16x3__gaussian_flows.json",
    "randomized/high/70__manhattan_16x3__gaussian_flows.json",
    "randomized/high/71__manhattan_16x3__gaussian_flows.json",
    "randomized/high/72__manhattan_16x3__gaussian_flows.json",
    "randomized/high/73__manhattan_16x3__gaussian_flows.json",
    "randomized/high/74__manhattan_16x3__gaussian_flows.json",
    "randomized/high/75__manhattan_16x3__gaussian_flows.json",
    "randomized/high/76__manhattan_16x3__gaussian_flows.json",
    "randomized/high/77__manhattan_16x3__gaussian_flows.json",
    "randomized/high/78__manhattan_16x3__gaussian_flows.json",
    "randomized/high/79__manhattan_16x3__gaussian_flows.json",
    "randomized/high/80__manhattan_16x3__gaussian_flows.json",
    "randomized/high/81__manhattan_16x3__gaussian_flows.json",
    "randomized/high/82__manhattan_16x3__gaussian_flows.json",
    "randomized/high/83__manhattan_16x3__gaussian_flows.json",
    "randomized/high/84__manhattan_16x3__gaussian_flows.json",
    "randomized/high/85__manhattan_16x3__gaussian_flows.json",
    "randomized/high/86__manhattan_16x3__gaussian_flows.json",
    "randomized/high/87__manhattan_16x3__gaussian_flows.json",
    "randomized/high/88__manhattan_16x3__gaussian_flows.json",
    "randomized/high/89__manhattan_16x3__gaussian_flows.json",
    "randomized/high/90__manhattan_16x3__gaussian_flows.json",
    "randomized/high/91__manhattan_16x3__gaussian_flows.json",
    "randomized/high/92__manhattan_16x3__gaussian_flows.json",
    "randomized/high/93__manhattan_16x3__gaussian_flows.json",
    "randomized/high/94__manhattan_16x3__gaussian_flows.json",
    "randomized/high/95__manhattan_16x3__gaussian_flows.json",
    "randomized/high/96__manhattan_16x3__gaussian_flows.json",
    "randomized/high/97__manhattan_16x3__gaussian_flows.json",
    "randomized/high/98__manhattan_16x3__gaussian_flows.json",
    "randomized/high/99__manhattan_16x3__gaussian_flows.json",
  ]

signal:
  action_space: phase_selection
  round_robin: False
  reward_function: queue_length