cityflow:
  roadnet_file: 4x4_roadnet.json
  flow_file: 4x4_roadnet_500.json
  roadnet_log_file: "frontend/web/roadnet_log_file.json"
  replay_log_file: "frontend/web/replay_log_file.txt"
  save_replay: False



