cityflow:
  roadnet_file: 3x3_cityflow_grid.json
  flow_file: 3x3_cityflow_grid_flows.json
  roadnet_log_file: "frontend/web/roadnet_log_file.json"
  replay_log_file: "frontend/web/replay_log_file.txt"
  save_replay: False
