cityflow:
  # phase_sequence: [1, 0, 3, 0, 2, 0, 4, 0]  # 0 is a common yellow phase
  roadnet_file: syn_1x3_roadnet.json
  flow_rate_type: "random"
  flow_files: [
    "syn_1x3_uniform_0_600.json",
    "syn_1x3_uniform_1_625.json",
    "syn_1x3_uniform_1_650.json",
    "syn_1x3_uniform_1_675.json",
    "syn_1x3_uniform_1_700.json",
    "syn_1x3_uniform_1_725.json",
    "syn_1x3_uniform_1_750.json",
    "syn_1x3_uniform_2_625.json",
    "syn_1x3_uniform_2_650.json",
    "syn_1x3_uniform_2_675.json",
    "syn_1x3_uniform_2_700.json",
    "syn_1x3_uniform_2_725.json",
    "syn_1x3_uniform_2_750.json",
    "syn_1x3_uniform_3_625.json",
    "syn_1x3_uniform_3_650.json",
    "syn_1x3_uniform_3_675.json",
    "syn_1x3_uniform_3_700.json",
    "syn_1x3_uniform_3_725.json",
    "syn_1x3_uniform_3_750.json",
  ]
  roadnet_log_file: "roadnet_log_file.json"
  replay_log_file: "replay_log_file.txt"
  save_replay: False
  episode_limit: 3600

signal:
  visibility: 20
  reward_function: queue_length
  max_green_time: 60