cityflow:
  # phase_sequence: [1, 0, 3, 0, 2, 0, 4, 0]  # 0 is a common yellow phase
  roadnet_file: syn_1x3_roadnet.json
  flow_rate_type: "random"
  flow_files: [
    "syn_1x3_uniform_0.json",
    "syn_1x3_uniform_1.json",
    "syn_1x3_uniform_2.json",
    "syn_1x3_uniform_3.json",
  ]
  roadnet_log_file: "roadnet_log_file.json"
  replay_log_file: "replay_log_file.txt"
  save_replay: False

signal:
  visibility: 20
  reward_function: queue_length
  min_green_time: 20
  max_green_time: 60