# https://github.com/Pi-Star-Lab/RESCO/tree/main
# SUMO parameters
sumo:
  render: False

# Network parameters
network:
  network_type: real # (synthetic, real)

misc:
  return_lane_stats: False
  return_agent_stats: False
