cityflow:
  plan: [5, 30, 30, 30, 30, 30, 30, 30, 30]
  # phase_sequence: [1, 0, 3, 0, 2, 0, 4, 0]  # 0 is a common yellow phase
  roadnet_file: "roadnet_3_4.json"
  flow_file: "anon_3_4_jinan_real.json"
  roadnet_log_file: "roadnet_log_file.json"
  replay_log_file: "replay_log_file.txt"
  save_replay: False
  flow_rate_type: "random"
  flow_classes: ["normal", "flow_disrupted", "link_disrupted"]
  train_normal_flow_files: [
    "train/normal/0__jinan_3_4__gaussian_700_flows.json",
    "train/normal/1__jinan_3_4__gaussian_700_flows.json",
    "train/normal/2__jinan_3_4__gaussian_700_flows.json",
    "train/normal/3__jinan_3_4__gaussian_700_flows.json",
    "train/normal/4__jinan_3_4__gaussian_700_flows.json",
    "train/normal/5__jinan_3_4__gaussian_700_flows.json",
    "train/normal/6__jinan_3_4__gaussian_700_flows.json",
    "train/normal/7__jinan_3_4__gaussian_700_flows.json",
    "train/normal/8__jinan_3_4__gaussian_700_flows.json",
    "train/normal/9__jinan_3_4__gaussian_700_flows.json",
  ]
  train_flow_disrupted_flow_files: [
    "train/flow_disrupted/0__jinan_3_4__gaussian_600_flows.json",
    "train/flow_disrupted/0__jinan_3_4__gaussian_750_flows.json",
    "train/flow_disrupted/0__jinan_3_4__gaussian_800_flows.json",
    "train/flow_disrupted/1__jinan_3_4__gaussian_600_flows.json",
    "train/flow_disrupted/1__jinan_3_4__gaussian_750_flows.json",
    "train/flow_disrupted/1__jinan_3_4__gaussian_800_flows.json",
    "train/flow_disrupted/2__jinan_3_4__gaussian_600_flows.json",
    "train/flow_disrupted/2__jinan_3_4__gaussian_750_flows.json",
    "train/flow_disrupted/2__jinan_3_4__gaussian_800_flows.json",
    "train/flow_disrupted/3__jinan_3_4__gaussian_600_flows.json",
    "train/flow_disrupted/3__jinan_3_4__gaussian_750_flows.json",
    "train/flow_disrupted/3__jinan_3_4__gaussian_800_flows.json",
    "train/flow_disrupted/4__jinan_3_4__gaussian_600_flows.json",
    "train/flow_disrupted/4__jinan_3_4__gaussian_750_flows.json",
    "train/flow_disrupted/4__jinan_3_4__gaussian_800_flows.json",
    "train/flow_disrupted/5__jinan_3_4__gaussian_600_flows.json",
    "train/flow_disrupted/5__jinan_3_4__gaussian_750_flows.json",
    "train/flow_disrupted/5__jinan_3_4__gaussian_800_flows.json",
    "train/flow_disrupted/6__jinan_3_4__gaussian_600_flows.json",
    "train/flow_disrupted/6__jinan_3_4__gaussian_750_flows.json",
    "train/flow_disrupted/6__jinan_3_4__gaussian_800_flows.json",
    "train/flow_disrupted/7__jinan_3_4__gaussian_600_flows.json",
    "train/flow_disrupted/7__jinan_3_4__gaussian_750_flows.json",
    "train/flow_disrupted/7__jinan_3_4__gaussian_800_flows.json",
    "train/flow_disrupted/8__jinan_3_4__gaussian_600_flows.json",
    "train/flow_disrupted/8__jinan_3_4__gaussian_750_flows.json",
    "train/flow_disrupted/8__jinan_3_4__gaussian_800_flows.json",
    "train/flow_disrupted/9__jinan_3_4__gaussian_600_flows.json",
    "train/flow_disrupted/9__jinan_3_4__gaussian_750_flows.json",
    "train/flow_disrupted/9__jinan_3_4__gaussian_800_flows.json",
  ]
  train_link_disrupted_flow_files: [
    "train/link_disrupted/0__jinan_3_4__dr_0.1__gaussian_700_flows.json",
    "train/link_disrupted/0__jinan_3_4__dr_0.3__gaussian_700_flows.json",
    "train/link_disrupted/1__jinan_3_4__dr_0.1__gaussian_700_flows.json",
    "train/link_disrupted/1__jinan_3_4__dr_0.3__gaussian_700_flows.json",
    "train/link_disrupted/2__jinan_3_4__dr_0.1__gaussian_700_flows.json",
    "train/link_disrupted/2__jinan_3_4__dr_0.3__gaussian_700_flows.json",
    "train/link_disrupted/3__jinan_3_4__dr_0.1__gaussian_700_flows.json",
    "train/link_disrupted/3__jinan_3_4__dr_0.3__gaussian_700_flows.json",
    "train/link_disrupted/4__jinan_3_4__dr_0.1__gaussian_700_flows.json",
    "train/link_disrupted/4__jinan_3_4__dr_0.3__gaussian_700_flows.json",
    "train/link_disrupted/5__jinan_3_4__dr_0.1__gaussian_700_flows.json",
    "train/link_disrupted/5__jinan_3_4__dr_0.3__gaussian_700_flows.json",
    "train/link_disrupted/6__jinan_3_4__dr_0.1__gaussian_700_flows.json",
    "train/link_disrupted/6__jinan_3_4__dr_0.3__gaussian_700_flows.json",
    "train/link_disrupted/7__jinan_3_4__dr_0.1__gaussian_700_flows.json",
    "train/link_disrupted/7__jinan_3_4__dr_0.3__gaussian_700_flows.json",
    "train/link_disrupted/8__jinan_3_4__dr_0.1__gaussian_700_flows.json",
    "train/link_disrupted/8__jinan_3_4__dr_0.3__gaussian_700_flows.json",
    "train/link_disrupted/9__jinan_3_4__dr_0.1__gaussian_700_flows.json",
    "train/link_disrupted/9__jinan_3_4__dr_0.3__gaussian_700_flows.json",
  ]
  test_flow_disrupted_flow_files: [
    "test/flow_disrupted/0__jinan_3_4__gaussian_650_flows.json",
    "test/flow_disrupted/0__jinan_3_4__gaussian_850_flows.json",
    "test/flow_disrupted/0__jinan_3_4__gaussian_900_flows.json",
    "test/flow_disrupted/1__jinan_3_4__gaussian_650_flows.json",
    "test/flow_disrupted/1__jinan_3_4__gaussian_850_flows.json",
    "test/flow_disrupted/1__jinan_3_4__gaussian_900_flows.json",
    "test/flow_disrupted/2__jinan_3_4__gaussian_650_flows.json",
    "test/flow_disrupted/2__jinan_3_4__gaussian_850_flows.json",
    "test/flow_disrupted/2__jinan_3_4__gaussian_900_flows.json",
    "test/flow_disrupted/3__jinan_3_4__gaussian_650_flows.json",
    "test/flow_disrupted/3__jinan_3_4__gaussian_850_flows.json",
    "test/flow_disrupted/3__jinan_3_4__gaussian_900_flows.json",
    "test/flow_disrupted/4__jinan_3_4__gaussian_650_flows.json",
    "test/flow_disrupted/4__jinan_3_4__gaussian_850_flows.json",
    "test/flow_disrupted/4__jinan_3_4__gaussian_900_flows.json",
    "test/flow_disrupted/5__jinan_3_4__gaussian_650_flows.json",
    "test/flow_disrupted/5__jinan_3_4__gaussian_850_flows.json",
    "test/flow_disrupted/5__jinan_3_4__gaussian_900_flows.json",
    "test/flow_disrupted/6__jinan_3_4__gaussian_650_flows.json",
    "test/flow_disrupted/6__jinan_3_4__gaussian_850_flows.json",
    "test/flow_disrupted/6__jinan_3_4__gaussian_900_flows.json",
    "test/flow_disrupted/7__jinan_3_4__gaussian_650_flows.json",
    "test/flow_disrupted/7__jinan_3_4__gaussian_850_flows.json",
    "test/flow_disrupted/7__jinan_3_4__gaussian_900_flows.json",
    "test/flow_disrupted/8__jinan_3_4__gaussian_650_flows.json",
    "test/flow_disrupted/8__jinan_3_4__gaussian_850_flows.json",
    "test/flow_disrupted/8__jinan_3_4__gaussian_900_flows.json",
    "test/flow_disrupted/9__jinan_3_4__gaussian_650_flows.json",
    "test/flow_disrupted/9__jinan_3_4__gaussian_850_flows.json",
    "test/flow_disrupted/9__jinan_3_4__gaussian_900_flows.json",
  ]
  test_link_disrupted_flow_files: [
    "test/link_disrupted/0__jinan_3_4__dr_0.2__gaussian_700_flows.json",
    "test/link_disrupted/0__jinan_3_4__dr_0.4__gaussian_700_flows.json",
    "test/link_disrupted/1__jinan_3_4__dr_0.2__gaussian_700_flows.json",
    "test/link_disrupted/1__jinan_3_4__dr_0.4__gaussian_700_flows.json",
    "test/link_disrupted/2__jinan_3_4__dr_0.2__gaussian_700_flows.json",
    "test/link_disrupted/2__jinan_3_4__dr_0.4__gaussian_700_flows.json",
    "test/link_disrupted/3__jinan_3_4__dr_0.2__gaussian_700_flows.json",
    "test/link_disrupted/3__jinan_3_4__dr_0.4__gaussian_700_flows.json",
    "test/link_disrupted/4__jinan_3_4__dr_0.2__gaussian_700_flows.json",
    "test/link_disrupted/4__jinan_3_4__dr_0.4__gaussian_700_flows.json",
    "test/link_disrupted/5__jinan_3_4__dr_0.2__gaussian_700_flows.json",
    "test/link_disrupted/5__jinan_3_4__dr_0.4__gaussian_700_flows.json",
    "test/link_disrupted/6__jinan_3_4__dr_0.2__gaussian_700_flows.json",
    "test/link_disrupted/6__jinan_3_4__dr_0.4__gaussian_700_flows.json",
    "test/link_disrupted/7__jinan_3_4__dr_0.2__gaussian_700_flows.json",
    "test/link_disrupted/7__jinan_3_4__dr_0.4__gaussian_700_flows.json",
    "test/link_disrupted/8__jinan_3_4__dr_0.2__gaussian_700_flows.json",
    "test/link_disrupted/8__jinan_3_4__dr_0.4__gaussian_700_flows.json",
    "test/link_disrupted/9__jinan_3_4__dr_0.2__gaussian_700_flows.json",
    "test/link_disrupted/9__jinan_3_4__dr_0.4__gaussian_700_flows.json",
  ]

signal:
  action_space: phase_selection
  round_robin: False
  reward_function: queue_length
