cityflow:
  plan: [5, 30, 30, 30, 30, 30, 30, 30, 30]
  # phase_sequence: [1, 0, 3, 0, 2, 0, 4, 0]  # 0 is a common yellow phase
  roadnet_file: "roadnet_3_4.json"
  flow_file: "anon_3_4_jinan_real.json"
  roadnet_log_file: "roadnet_log_file.json"
  replay_log_file: "replay_log_file.txt"
  save_replay: False
  flow_rate_type: "random"
  flow_files: [
    "randomized/medium/0__jinan_3_4__gaussian_flows.json",
    "randomized/medium/1__jinan_3_4__gaussian_flows.json",
    "randomized/medium/2__jinan_3_4__gaussian_flows.json",
    "randomized/medium/3__jinan_3_4__gaussian_flows.json",
    "randomized/medium/4__jinan_3_4__gaussian_flows.json",
    "randomized/medium/5__jinan_3_4__gaussian_flows.json",
    "randomized/medium/6__jinan_3_4__gaussian_flows.json",
    "randomized/medium/7__jinan_3_4__gaussian_flows.json",
    "randomized/medium/8__jinan_3_4__gaussian_flows.json",
    "randomized/medium/9__jinan_3_4__gaussian_flows.json",
    "randomized/medium/10__jinan_3_4__gaussian_flows.json",
    "randomized/medium/11__jinan_3_4__gaussian_flows.json",
    "randomized/medium/12__jinan_3_4__gaussian_flows.json",
    "randomized/medium/13__jinan_3_4__gaussian_flows.json",
    "randomized/medium/14__jinan_3_4__gaussian_flows.json",
    "randomized/medium/15__jinan_3_4__gaussian_flows.json",
    "randomized/medium/16__jinan_3_4__gaussian_flows.json",
    "randomized/medium/17__jinan_3_4__gaussian_flows.json",
    "randomized/medium/18__jinan_3_4__gaussian_flows.json",
    "randomized/medium/19__jinan_3_4__gaussian_flows.json",
    "randomized/medium/20__jinan_3_4__gaussian_flows.json",
    "randomized/medium/21__jinan_3_4__gaussian_flows.json",
    "randomized/medium/22__jinan_3_4__gaussian_flows.json",
    "randomized/medium/23__jinan_3_4__gaussian_flows.json",
    "randomized/medium/24__jinan_3_4__gaussian_flows.json",
    "randomized/medium/25__jinan_3_4__gaussian_flows.json",
    "randomized/medium/26__jinan_3_4__gaussian_flows.json",
    "randomized/medium/27__jinan_3_4__gaussian_flows.json",
    "randomized/medium/28__jinan_3_4__gaussian_flows.json",
    "randomized/medium/29__jinan_3_4__gaussian_flows.json",
    "randomized/medium/30__jinan_3_4__gaussian_flows.json",
    "randomized/medium/31__jinan_3_4__gaussian_flows.json",
    "randomized/medium/32__jinan_3_4__gaussian_flows.json",
    "randomized/medium/33__jinan_3_4__gaussian_flows.json",
    "randomized/medium/34__jinan_3_4__gaussian_flows.json",
    "randomized/medium/35__jinan_3_4__gaussian_flows.json",
    "randomized/medium/36__jinan_3_4__gaussian_flows.json",
    "randomized/medium/37__jinan_3_4__gaussian_flows.json",
    "randomized/medium/38__jinan_3_4__gaussian_flows.json",
    "randomized/medium/39__jinan_3_4__gaussian_flows.json",
    "randomized/medium/40__jinan_3_4__gaussian_flows.json",
    "randomized/medium/41__jinan_3_4__gaussian_flows.json",
    "randomized/medium/42__jinan_3_4__gaussian_flows.json",
    "randomized/medium/43__jinan_3_4__gaussian_flows.json",
    "randomized/medium/44__jinan_3_4__gaussian_flows.json",
    "randomized/medium/45__jinan_3_4__gaussian_flows.json",
    "randomized/medium/46__jinan_3_4__gaussian_flows.json",
    "randomized/medium/47__jinan_3_4__gaussian_flows.json",
    "randomized/medium/48__jinan_3_4__gaussian_flows.json",
    "randomized/medium/49__jinan_3_4__gaussian_flows.json",
    "randomized/medium/50__jinan_3_4__gaussian_flows.json",
    "randomized/medium/51__jinan_3_4__gaussian_flows.json",
    "randomized/medium/52__jinan_3_4__gaussian_flows.json",
    "randomized/medium/53__jinan_3_4__gaussian_flows.json",
    "randomized/medium/54__jinan_3_4__gaussian_flows.json",
    "randomized/medium/55__jinan_3_4__gaussian_flows.json",
    "randomized/medium/56__jinan_3_4__gaussian_flows.json",
    "randomized/medium/57__jinan_3_4__gaussian_flows.json",
    "randomized/medium/58__jinan_3_4__gaussian_flows.json",
    "randomized/medium/59__jinan_3_4__gaussian_flows.json",
    "randomized/medium/60__jinan_3_4__gaussian_flows.json",
    "randomized/medium/61__jinan_3_4__gaussian_flows.json",
    "randomized/medium/62__jinan_3_4__gaussian_flows.json",
    "randomized/medium/63__jinan_3_4__gaussian_flows.json",
    "randomized/medium/64__jinan_3_4__gaussian_flows.json",
    "randomized/medium/65__jinan_3_4__gaussian_flows.json",
    "randomized/medium/66__jinan_3_4__gaussian_flows.json",
    "randomized/medium/67__jinan_3_4__gaussian_flows.json",
    "randomized/medium/68__jinan_3_4__gaussian_flows.json",
    "randomized/medium/69__jinan_3_4__gaussian_flows.json",
    "randomized/medium/70__jinan_3_4__gaussian_flows.json",
    "randomized/medium/71__jinan_3_4__gaussian_flows.json",
    "randomized/medium/72__jinan_3_4__gaussian_flows.json",
    "randomized/medium/73__jinan_3_4__gaussian_flows.json",
    "randomized/medium/74__jinan_3_4__gaussian_flows.json",
    "randomized/medium/75__jinan_3_4__gaussian_flows.json",
    "randomized/medium/76__jinan_3_4__gaussian_flows.json",
    "randomized/medium/77__jinan_3_4__gaussian_flows.json",
    "randomized/medium/78__jinan_3_4__gaussian_flows.json",
    "randomized/medium/79__jinan_3_4__gaussian_flows.json",
    "randomized/medium/80__jinan_3_4__gaussian_flows.json",
    "randomized/medium/81__jinan_3_4__gaussian_flows.json",
    "randomized/medium/82__jinan_3_4__gaussian_flows.json",
    "randomized/medium/83__jinan_3_4__gaussian_flows.json",
    "randomized/medium/84__jinan_3_4__gaussian_flows.json",
    "randomized/medium/85__jinan_3_4__gaussian_flows.json",
    "randomized/medium/86__jinan_3_4__gaussian_flows.json",
    "randomized/medium/87__jinan_3_4__gaussian_flows.json",
    "randomized/medium/88__jinan_3_4__gaussian_flows.json",
    "randomized/medium/89__jinan_3_4__gaussian_flows.json",
    "randomized/medium/90__jinan_3_4__gaussian_flows.json",
    "randomized/medium/91__jinan_3_4__gaussian_flows.json",
    "randomized/medium/92__jinan_3_4__gaussian_flows.json",
    "randomized/medium/93__jinan_3_4__gaussian_flows.json",
    "randomized/medium/94__jinan_3_4__gaussian_flows.json",
    "randomized/medium/95__jinan_3_4__gaussian_flows.json",
    "randomized/medium/96__jinan_3_4__gaussian_flows.json",
    "randomized/medium/97__jinan_3_4__gaussian_flows.json",
    "randomized/medium/98__jinan_3_4__gaussian_flows.json",
    "randomized/medium/99__jinan_3_4__gaussian_flows.json",
  ]

signal:
  action_space: phase_selection
  round_robin: False
  reward_function: queue_length
