cityflow:
  plan: [5, 30, 30, 30, 30, 30, 30, 30, 30]
  # phase_sequence: [1, 0, 3, 0, 2, 0, 4, 0]  # 0 is a common yellow phase
  roadnet_file: "roadnet_3_4.json"
  flow_file: "randomized/0__jinan_3_4__gaussian_flows.json"
  roadnet_log_file: "roadnet_log_file.json"
  replay_log_file: "replay_log_file.txt"
  save_replay: False
  flow_rate_type: "constant"
  flow_files: [
    "randomized/0__jinan_3_4__gaussian_flows.json",
    "randomized/1__jinan_3_4__gaussian_flows.json",
    "randomized/2__jinan_3_4__gaussian_flows.json",
    "randomized/3__jinan_3_4__gaussian_flows.json",
    "randomized/4__jinan_3_4__gaussian_flows.json",
    "randomized/5__jinan_3_4__gaussian_flows.json",
    "randomized/6__jinan_3_4__gaussian_flows.json",
    "randomized/7__jinan_3_4__gaussian_flows.json",
    "randomized/8__jinan_3_4__gaussian_flows.json",
    "randomized/9__jinan_3_4__gaussian_flows.json",
    "randomized/10__jinan_3_4__gaussian_flows.json",
    "randomized/11__jinan_3_4__gaussian_flows.json",
    "randomized/12__jinan_3_4__gaussian_flows.json",
    "randomized/13__jinan_3_4__gaussian_flows.json",
    "randomized/14__jinan_3_4__gaussian_flows.json",
    "randomized/15__jinan_3_4__gaussian_flows.json",
    "randomized/16__jinan_3_4__gaussian_flows.json",
    "randomized/17__jinan_3_4__gaussian_flows.json",
    "randomized/18__jinan_3_4__gaussian_flows.json",
    "randomized/19__jinan_3_4__gaussian_flows.json",
    "randomized/20__jinan_3_4__gaussian_flows.json",
    "randomized/21__jinan_3_4__gaussian_flows.json",
    "randomized/22__jinan_3_4__gaussian_flows.json",
    "randomized/23__jinan_3_4__gaussian_flows.json",
    "randomized/24__jinan_3_4__gaussian_flows.json",
    "randomized/25__jinan_3_4__gaussian_flows.json",
    "randomized/26__jinan_3_4__gaussian_flows.json",
    "randomized/27__jinan_3_4__gaussian_flows.json",
    "randomized/28__jinan_3_4__gaussian_flows.json",
    "randomized/29__jinan_3_4__gaussian_flows.json",
    "randomized/30__jinan_3_4__gaussian_flows.json",
    "randomized/31__jinan_3_4__gaussian_flows.json",
    "randomized/32__jinan_3_4__gaussian_flows.json",
    "randomized/33__jinan_3_4__gaussian_flows.json",
    "randomized/34__jinan_3_4__gaussian_flows.json",
    "randomized/35__jinan_3_4__gaussian_flows.json",
    "randomized/36__jinan_3_4__gaussian_flows.json",
    "randomized/37__jinan_3_4__gaussian_flows.json",
    "randomized/38__jinan_3_4__gaussian_flows.json",
    "randomized/39__jinan_3_4__gaussian_flows.json",
    "randomized/40__jinan_3_4__gaussian_flows.json",
    "randomized/41__jinan_3_4__gaussian_flows.json",
    "randomized/42__jinan_3_4__gaussian_flows.json",
    "randomized/43__jinan_3_4__gaussian_flows.json",
    "randomized/44__jinan_3_4__gaussian_flows.json",
    "randomized/45__jinan_3_4__gaussian_flows.json",
    "randomized/46__jinan_3_4__gaussian_flows.json",
    "randomized/47__jinan_3_4__gaussian_flows.json",
    "randomized/48__jinan_3_4__gaussian_flows.json",
    "randomized/49__jinan_3_4__gaussian_flows.json",
    "randomized/50__jinan_3_4__gaussian_flows.json",
    "randomized/51__jinan_3_4__gaussian_flows.json",
    "randomized/52__jinan_3_4__gaussian_flows.json",
    "randomized/53__jinan_3_4__gaussian_flows.json",
    "randomized/54__jinan_3_4__gaussian_flows.json",
    "randomized/55__jinan_3_4__gaussian_flows.json",
    "randomized/56__jinan_3_4__gaussian_flows.json",
    "randomized/57__jinan_3_4__gaussian_flows.json",
    "randomized/58__jinan_3_4__gaussian_flows.json",
    "randomized/59__jinan_3_4__gaussian_flows.json",
    "randomized/60__jinan_3_4__gaussian_flows.json",
    "randomized/61__jinan_3_4__gaussian_flows.json",
    "randomized/62__jinan_3_4__gaussian_flows.json",
    "randomized/63__jinan_3_4__gaussian_flows.json",
    "randomized/64__jinan_3_4__gaussian_flows.json",
    "randomized/65__jinan_3_4__gaussian_flows.json",
    "randomized/66__jinan_3_4__gaussian_flows.json",
    "randomized/67__jinan_3_4__gaussian_flows.json",
    "randomized/68__jinan_3_4__gaussian_flows.json",
    "randomized/69__jinan_3_4__gaussian_flows.json",
    "randomized/70__jinan_3_4__gaussian_flows.json",
    "randomized/71__jinan_3_4__gaussian_flows.json",
    "randomized/72__jinan_3_4__gaussian_flows.json",
    "randomized/73__jinan_3_4__gaussian_flows.json",
    "randomized/74__jinan_3_4__gaussian_flows.json",
    "randomized/75__jinan_3_4__gaussian_flows.json",
    "randomized/76__jinan_3_4__gaussian_flows.json",
    "randomized/77__jinan_3_4__gaussian_flows.json",
    "randomized/78__jinan_3_4__gaussian_flows.json",
    "randomized/79__jinan_3_4__gaussian_flows.json",
    "randomized/80__jinan_3_4__gaussian_flows.json",
    "randomized/81__jinan_3_4__gaussian_flows.json",
    "randomized/82__jinan_3_4__gaussian_flows.json",
    "randomized/83__jinan_3_4__gaussian_flows.json",
    "randomized/84__jinan_3_4__gaussian_flows.json",
    "randomized/85__jinan_3_4__gaussian_flows.json",
    "randomized/86__jinan_3_4__gaussian_flows.json",
    "randomized/87__jinan_3_4__gaussian_flows.json",
    "randomized/88__jinan_3_4__gaussian_flows.json",
    "randomized/89__jinan_3_4__gaussian_flows.json",
    "randomized/90__jinan_3_4__gaussian_flows.json",
    "randomized/91__jinan_3_4__gaussian_flows.json",
    "randomized/92__jinan_3_4__gaussian_flows.json",
    "randomized/93__jinan_3_4__gaussian_flows.json",
    "randomized/94__jinan_3_4__gaussian_flows.json",
    "randomized/95__jinan_3_4__gaussian_flows.json",
    "randomized/96__jinan_3_4__gaussian_flows.json",
    "randomized/97__jinan_3_4__gaussian_flows.json",
    "randomized/98__jinan_3_4__gaussian_flows.json",
    "randomized/99__jinan_3_4__gaussian_flows.json",
  ]

signal:
  action_space: phase_selection
  round_robin: False
  reward_function: queue_length
