cityflow:
  plan: [5, 30, 30, 30, 30, 30, 30, 30, 30]
  # phase_sequence: [1, 0, 3, 0, 2, 0, 4, 0]  # 0 is a common yellow phase
  roadnet_file: "roadnet_3_4.json"
  flow_file: "anon_3_4_jinan_real.json"
  roadnet_log_file: "roadnet_log_file.json"
  replay_log_file: "replay_log_file.txt"
  save_replay: False
  flow_rate_type: "sequential"
  flow_files: [
    "randomized/anon_3_4_jinan_real_0.json",
    "randomized/anon_3_4_jinan_real_1.json",
    "randomized/anon_3_4_jinan_real_2.json",
    "randomized/anon_3_4_jinan_real_3.json",
    "randomized/anon_3_4_jinan_real_4.json",
    "randomized/anon_3_4_jinan_real_5.json",
    "randomized/anon_3_4_jinan_real_6.json",
    "randomized/anon_3_4_jinan_real_7.json",
    "randomized/anon_3_4_jinan_real_8.json",
    "randomized/anon_3_4_jinan_real_9.json",
    "randomized/anon_3_4_jinan_real_10.json",
    "randomized/anon_3_4_jinan_real_11.json",
    "randomized/anon_3_4_jinan_real_12.json",
    "randomized/anon_3_4_jinan_real_13.json",
    "randomized/anon_3_4_jinan_real_14.json",
    "randomized/anon_3_4_jinan_real_15.json",
    "randomized/anon_3_4_jinan_real_16.json",
    "randomized/anon_3_4_jinan_real_17.json",
    "randomized/anon_3_4_jinan_real_18.json",
    "randomized/anon_3_4_jinan_real_19.json",
    "randomized/anon_3_4_jinan_real_20.json",
    "randomized/anon_3_4_jinan_real_21.json",
    "randomized/anon_3_4_jinan_real_22.json",
    "randomized/anon_3_4_jinan_real_23.json",
    "randomized/anon_3_4_jinan_real_24.json",
    "randomized/anon_3_4_jinan_real_25.json",
    "randomized/anon_3_4_jinan_real_26.json",
    "randomized/anon_3_4_jinan_real_27.json",
    "randomized/anon_3_4_jinan_real_28.json",
    "randomized/anon_3_4_jinan_real_29.json",
    "randomized/anon_3_4_jinan_real_30.json",
    "randomized/anon_3_4_jinan_real_31.json",
    "randomized/anon_3_4_jinan_real_32.json",
    "randomized/anon_3_4_jinan_real_33.json",
    "randomized/anon_3_4_jinan_real_34.json",
    "randomized/anon_3_4_jinan_real_35.json",
    "randomized/anon_3_4_jinan_real_36.json",
    "randomized/anon_3_4_jinan_real_37.json",
    "randomized/anon_3_4_jinan_real_38.json",
    "randomized/anon_3_4_jinan_real_39.json",
    "randomized/anon_3_4_jinan_real_40.json",
    "randomized/anon_3_4_jinan_real_41.json",
    "randomized/anon_3_4_jinan_real_42.json",
    "randomized/anon_3_4_jinan_real_43.json",
    "randomized/anon_3_4_jinan_real_44.json",
    "randomized/anon_3_4_jinan_real_45.json",
    "randomized/anon_3_4_jinan_real_46.json",
    "randomized/anon_3_4_jinan_real_47.json",
    "randomized/anon_3_4_jinan_real_48.json",
    "randomized/anon_3_4_jinan_real_49.json",
    "randomized/anon_3_4_jinan_real_50.json",
    "randomized/anon_3_4_jinan_real_51.json",
    "randomized/anon_3_4_jinan_real_52.json",
    "randomized/anon_3_4_jinan_real_53.json",
    "randomized/anon_3_4_jinan_real_54.json",
    "randomized/anon_3_4_jinan_real_55.json",
    "randomized/anon_3_4_jinan_real_56.json",
    "randomized/anon_3_4_jinan_real_57.json",
    "randomized/anon_3_4_jinan_real_58.json",
    "randomized/anon_3_4_jinan_real_59.json",
    "randomized/anon_3_4_jinan_real_60.json",
    "randomized/anon_3_4_jinan_real_61.json",
    "randomized/anon_3_4_jinan_real_62.json",
    "randomized/anon_3_4_jinan_real_63.json",
    "randomized/anon_3_4_jinan_real_64.json",
    "randomized/anon_3_4_jinan_real_65.json",
    "randomized/anon_3_4_jinan_real_66.json",
    "randomized/anon_3_4_jinan_real_67.json",
    "randomized/anon_3_4_jinan_real_68.json",
    "randomized/anon_3_4_jinan_real_69.json",
    "randomized/anon_3_4_jinan_real_70.json",
    "randomized/anon_3_4_jinan_real_71.json",
    "randomized/anon_3_4_jinan_real_72.json",
    "randomized/anon_3_4_jinan_real_73.json",
    "randomized/anon_3_4_jinan_real_74.json",
    "randomized/anon_3_4_jinan_real_75.json",
    "randomized/anon_3_4_jinan_real_76.json",
    "randomized/anon_3_4_jinan_real_77.json",
    "randomized/anon_3_4_jinan_real_78.json",
    "randomized/anon_3_4_jinan_real_79.json",
    "randomized/anon_3_4_jinan_real_80.json",
    "randomized/anon_3_4_jinan_real_81.json",
    "randomized/anon_3_4_jinan_real_82.json",
    "randomized/anon_3_4_jinan_real_83.json",
    "randomized/anon_3_4_jinan_real_84.json",
    "randomized/anon_3_4_jinan_real_85.json",
    "randomized/anon_3_4_jinan_real_86.json",
    "randomized/anon_3_4_jinan_real_87.json",
    "randomized/anon_3_4_jinan_real_88.json",
    "randomized/anon_3_4_jinan_real_89.json",
    "randomized/anon_3_4_jinan_real_90.json",
    "randomized/anon_3_4_jinan_real_91.json",
    "randomized/anon_3_4_jinan_real_92.json",
    "randomized/anon_3_4_jinan_real_93.json",
    "randomized/anon_3_4_jinan_real_94.json",
    "randomized/anon_3_4_jinan_real_95.json",
    "randomized/anon_3_4_jinan_real_96.json",
    "randomized/anon_3_4_jinan_real_97.json",
    "randomized/anon_3_4_jinan_real_98.json",
    "randomized/anon_3_4_jinan_real_99.json",
  ]


signal:
  action_space: phase_selection
  round_robin: False
  reward_function: queue_length
