cityflow:
  seed: 42
  thread_num: 1
  interval: 1.0
  rl_traffic_light: True
  lane_change: False
  delta_time: 5  # simulation steps between consecutive agent actions
  episode_limit: 360  # simulation seconds  n_steps = episode_limit / delta_time
  initial_wait_time: 0  # sim seconds to wait to populate the network
  veh_size_min_gap: 7.5  # vehicle_size + minimum gap or headway = 5 + 2.5
  roadnet_file: roadnet_16_1.json
  flow_file: 8th_ave.json
  flow_files: ["8th_ave.json", "9th_ave.json", "10th_ave.json", "11th_ave"]
  flow_rate_type: "constant"
  save_replay: True
  roadnet_log_file: "frontend/web/roadnet_log_file.json"
  replay_log_file: "frontend/web/replay_log_file.txt"

signal:
  action_space: "phase"  # (phase, phase_and_offset)
  yellow_time: 5
  min_green_time: 5
  max_green_time: 45
  round_robin: True
  # cycle_length: 50
  cycle_length: "adaptive"
