cityflow:
  plan: [5, 30, 30, 30, 30, 30, 30, 30, 30]
  # phase_sequence: [1, 0, 3, 0, 2, 0, 4, 0]  # 0 is a common yellow phase
  roadnet_file: roadnet_4_4.json
  flow_file: anon_4_4_hangzhou_real_5816.json
  roadnet_log_file: "frontend/web/roadnet_log_file.json"
  replay_log_file: "frontend/web/replay_log_file.txt"
  save_replay: False
  flow_rate_type: "sequential"
  flow_files: [
    "randomized/anon_4_4_hangzhou_real_5816_0.json",
    "randomized/anon_4_4_hangzhou_real_5816_1.json",
    "randomized/anon_4_4_hangzhou_real_5816_2.json",
    "randomized/anon_4_4_hangzhou_real_5816_3.json",
    "randomized/anon_4_4_hangzhou_real_5816_4.json",
    "randomized/anon_4_4_hangzhou_real_5816_5.json",
    "randomized/anon_4_4_hangzhou_real_5816_6.json",
    "randomized/anon_4_4_hangzhou_real_5816_7.json",
    "randomized/anon_4_4_hangzhou_real_5816_8.json",
    "randomized/anon_4_4_hangzhou_real_5816_9.json",
    "randomized/anon_4_4_hangzhou_real_5816_10.json",
    "randomized/anon_4_4_hangzhou_real_5816_11.json",
    "randomized/anon_4_4_hangzhou_real_5816_12.json",
    "randomized/anon_4_4_hangzhou_real_5816_13.json",
    "randomized/anon_4_4_hangzhou_real_5816_14.json",
    "randomized/anon_4_4_hangzhou_real_5816_15.json",
    "randomized/anon_4_4_hangzhou_real_5816_16.json",
    "randomized/anon_4_4_hangzhou_real_5816_17.json",
    "randomized/anon_4_4_hangzhou_real_5816_18.json",
    "randomized/anon_4_4_hangzhou_real_5816_19.json",
    "randomized/anon_4_4_hangzhou_real_5816_20.json",
    "randomized/anon_4_4_hangzhou_real_5816_21.json",
    "randomized/anon_4_4_hangzhou_real_5816_22.json",
    "randomized/anon_4_4_hangzhou_real_5816_23.json",
    "randomized/anon_4_4_hangzhou_real_5816_24.json",
    "randomized/anon_4_4_hangzhou_real_5816_25.json",
    "randomized/anon_4_4_hangzhou_real_5816_26.json",
    "randomized/anon_4_4_hangzhou_real_5816_27.json",
    "randomized/anon_4_4_hangzhou_real_5816_28.json",
    "randomized/anon_4_4_hangzhou_real_5816_29.json",
    "randomized/anon_4_4_hangzhou_real_5816_30.json",
    "randomized/anon_4_4_hangzhou_real_5816_31.json",
    "randomized/anon_4_4_hangzhou_real_5816_32.json",
    "randomized/anon_4_4_hangzhou_real_5816_33.json",
    "randomized/anon_4_4_hangzhou_real_5816_34.json",
    "randomized/anon_4_4_hangzhou_real_5816_35.json",
    "randomized/anon_4_4_hangzhou_real_5816_36.json",
    "randomized/anon_4_4_hangzhou_real_5816_37.json",
    "randomized/anon_4_4_hangzhou_real_5816_38.json",
    "randomized/anon_4_4_hangzhou_real_5816_39.json",
    "randomized/anon_4_4_hangzhou_real_5816_40.json",
    "randomized/anon_4_4_hangzhou_real_5816_41.json",
    "randomized/anon_4_4_hangzhou_real_5816_42.json",
    "randomized/anon_4_4_hangzhou_real_5816_43.json",
    "randomized/anon_4_4_hangzhou_real_5816_44.json",
    "randomized/anon_4_4_hangzhou_real_5816_45.json",
    "randomized/anon_4_4_hangzhou_real_5816_46.json",
    "randomized/anon_4_4_hangzhou_real_5816_47.json",
    "randomized/anon_4_4_hangzhou_real_5816_48.json",
    "randomized/anon_4_4_hangzhou_real_5816_49.json",
    "randomized/anon_4_4_hangzhou_real_5816_50.json",
    "randomized/anon_4_4_hangzhou_real_5816_51.json",
    "randomized/anon_4_4_hangzhou_real_5816_52.json",
    "randomized/anon_4_4_hangzhou_real_5816_53.json",
    "randomized/anon_4_4_hangzhou_real_5816_54.json",
    "randomized/anon_4_4_hangzhou_real_5816_55.json",
    "randomized/anon_4_4_hangzhou_real_5816_56.json",
    "randomized/anon_4_4_hangzhou_real_5816_57.json",
    "randomized/anon_4_4_hangzhou_real_5816_58.json",
    "randomized/anon_4_4_hangzhou_real_5816_59.json",
    "randomized/anon_4_4_hangzhou_real_5816_60.json",
    "randomized/anon_4_4_hangzhou_real_5816_61.json",
    "randomized/anon_4_4_hangzhou_real_5816_62.json",
    "randomized/anon_4_4_hangzhou_real_5816_63.json",
    "randomized/anon_4_4_hangzhou_real_5816_64.json",
    "randomized/anon_4_4_hangzhou_real_5816_65.json",
    "randomized/anon_4_4_hangzhou_real_5816_66.json",
    "randomized/anon_4_4_hangzhou_real_5816_67.json",
    "randomized/anon_4_4_hangzhou_real_5816_68.json",
    "randomized/anon_4_4_hangzhou_real_5816_69.json",
    "randomized/anon_4_4_hangzhou_real_5816_70.json",
    "randomized/anon_4_4_hangzhou_real_5816_71.json",
    "randomized/anon_4_4_hangzhou_real_5816_72.json",
    "randomized/anon_4_4_hangzhou_real_5816_73.json",
    "randomized/anon_4_4_hangzhou_real_5816_74.json",
    "randomized/anon_4_4_hangzhou_real_5816_75.json",
    "randomized/anon_4_4_hangzhou_real_5816_76.json",
    "randomized/anon_4_4_hangzhou_real_5816_77.json",
    "randomized/anon_4_4_hangzhou_real_5816_78.json",
    "randomized/anon_4_4_hangzhou_real_5816_79.json",
    "randomized/anon_4_4_hangzhou_real_5816_80.json",
    "randomized/anon_4_4_hangzhou_real_5816_81.json",
    "randomized/anon_4_4_hangzhou_real_5816_82.json",
    "randomized/anon_4_4_hangzhou_real_5816_83.json",
    "randomized/anon_4_4_hangzhou_real_5816_84.json",
    "randomized/anon_4_4_hangzhou_real_5816_85.json",
    "randomized/anon_4_4_hangzhou_real_5816_86.json",
    "randomized/anon_4_4_hangzhou_real_5816_87.json",
    "randomized/anon_4_4_hangzhou_real_5816_88.json",
    "randomized/anon_4_4_hangzhou_real_5816_89.json",
    "randomized/anon_4_4_hangzhou_real_5816_90.json",
    "randomized/anon_4_4_hangzhou_real_5816_91.json",
    "randomized/anon_4_4_hangzhou_real_5816_92.json",
    "randomized/anon_4_4_hangzhou_real_5816_93.json",
    "randomized/anon_4_4_hangzhou_real_5816_94.json",
    "randomized/anon_4_4_hangzhou_real_5816_95.json",
    "randomized/anon_4_4_hangzhou_real_5816_96.json",
    "randomized/anon_4_4_hangzhou_real_5816_97.json",
    "randomized/anon_4_4_hangzhou_real_5816_98.json",
    "randomized/anon_4_4_hangzhou_real_5816_99.json",
  ]

signal:
  action_space: phase_selection
  round_robin: False
  reward_function: queue_length