cityflow:
  plan: [5, 30, 30, 30, 30, 30, 30, 30, 30]
  # phase_sequence: [1, 0, 3, 0, 2, 0, 4, 0]  # 0 is a common yellow phase
  roadnet_file: "roadnet_4_4.json"
  flow_file: "anon_4_4_hangzhou_real.json"
  roadnet_log_file: "frontend/web/roadnet_log_file.json"
  replay_log_file: "frontend/web/replay_log_file.txt"
  save_replay: False
  flow_rate_type: "random"
  flow_files: [
    "randomized/low/0__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/1__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/2__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/3__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/4__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/5__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/6__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/7__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/8__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/9__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/10__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/11__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/12__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/13__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/14__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/15__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/16__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/17__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/18__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/19__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/20__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/21__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/22__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/23__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/24__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/25__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/26__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/27__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/28__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/29__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/30__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/31__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/32__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/33__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/34__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/35__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/36__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/37__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/38__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/39__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/40__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/41__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/42__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/43__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/44__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/45__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/46__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/47__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/48__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/49__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/50__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/51__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/52__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/53__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/54__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/55__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/56__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/57__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/58__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/59__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/60__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/61__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/62__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/63__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/64__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/65__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/66__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/67__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/68__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/69__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/70__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/71__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/72__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/73__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/74__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/75__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/76__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/77__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/78__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/79__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/80__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/81__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/82__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/83__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/84__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/85__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/86__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/87__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/88__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/89__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/90__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/91__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/92__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/93__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/94__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/95__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/96__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/97__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/98__hangzhou_4_4__gaussian_flows.json",
    "randomized/low/99__hangzhou_4_4__gaussian_flows.json",
  ]

signal:
  action_space: phase_selection
  round_robin: False
  reward_function: queue_length