cityflow:
  plan: [5, 30, 30, 30, 30, 30, 30, 30, 30]
  # phase_sequence: [1, 0, 3, 0, 2, 0, 4, 0]  # 0 is a common yellow phase
  roadnet_file: "roadnet_4_4.json"
  flow_file: "randomized/1__hangzhou_4_4__gaussian_flows.json"
  roadnet_log_file: "frontend/web/roadnet_log_file.json"
  replay_log_file: "frontend/web/replay_log_file.txt"
  save_replay: False
  flow_rate_type: "sequential"
  flow_files: [
    "randomized/0__hangzhou_4_4__gaussian_flows.json",
    "randomized/1__hangzhou_4_4__gaussian_flows.json",
    "randomized/2__hangzhou_4_4__gaussian_flows.json",
    "randomized/3__hangzhou_4_4__gaussian_flows.json",
    "randomized/4__hangzhou_4_4__gaussian_flows.json",
    "randomized/5__hangzhou_4_4__gaussian_flows.json",
    "randomized/6__hangzhou_4_4__gaussian_flows.json",
    "randomized/7__hangzhou_4_4__gaussian_flows.json",
    "randomized/8__hangzhou_4_4__gaussian_flows.json",
    "randomized/9__hangzhou_4_4__gaussian_flows.json",
    "randomized/10__hangzhou_4_4__gaussian_flows.json",
    "randomized/11__hangzhou_4_4__gaussian_flows.json",
    "randomized/12__hangzhou_4_4__gaussian_flows.json",
    "randomized/13__hangzhou_4_4__gaussian_flows.json",
    "randomized/14__hangzhou_4_4__gaussian_flows.json",
    "randomized/15__hangzhou_4_4__gaussian_flows.json",
    "randomized/16__hangzhou_4_4__gaussian_flows.json",
    "randomized/17__hangzhou_4_4__gaussian_flows.json",
    "randomized/18__hangzhou_4_4__gaussian_flows.json",
    "randomized/19__hangzhou_4_4__gaussian_flows.json",
    "randomized/20__hangzhou_4_4__gaussian_flows.json",
    "randomized/21__hangzhou_4_4__gaussian_flows.json",
    "randomized/22__hangzhou_4_4__gaussian_flows.json",
    "randomized/23__hangzhou_4_4__gaussian_flows.json",
    "randomized/24__hangzhou_4_4__gaussian_flows.json",
    "randomized/25__hangzhou_4_4__gaussian_flows.json",
    "randomized/26__hangzhou_4_4__gaussian_flows.json",
    "randomized/27__hangzhou_4_4__gaussian_flows.json",
    "randomized/28__hangzhou_4_4__gaussian_flows.json",
    "randomized/29__hangzhou_4_4__gaussian_flows.json",
    "randomized/30__hangzhou_4_4__gaussian_flows.json",
    "randomized/31__hangzhou_4_4__gaussian_flows.json",
    "randomized/32__hangzhou_4_4__gaussian_flows.json",
    "randomized/33__hangzhou_4_4__gaussian_flows.json",
    "randomized/34__hangzhou_4_4__gaussian_flows.json",
    "randomized/35__hangzhou_4_4__gaussian_flows.json",
    "randomized/36__hangzhou_4_4__gaussian_flows.json",
    "randomized/37__hangzhou_4_4__gaussian_flows.json",
    "randomized/38__hangzhou_4_4__gaussian_flows.json",
    "randomized/39__hangzhou_4_4__gaussian_flows.json",
    "randomized/40__hangzhou_4_4__gaussian_flows.json",
    "randomized/41__hangzhou_4_4__gaussian_flows.json",
    "randomized/42__hangzhou_4_4__gaussian_flows.json",
    "randomized/43__hangzhou_4_4__gaussian_flows.json",
    "randomized/44__hangzhou_4_4__gaussian_flows.json",
    "randomized/45__hangzhou_4_4__gaussian_flows.json",
    "randomized/46__hangzhou_4_4__gaussian_flows.json",
    "randomized/47__hangzhou_4_4__gaussian_flows.json",
    "randomized/48__hangzhou_4_4__gaussian_flows.json",
    "randomized/49__hangzhou_4_4__gaussian_flows.json",
    "randomized/50__hangzhou_4_4__gaussian_flows.json",
    "randomized/51__hangzhou_4_4__gaussian_flows.json",
    "randomized/52__hangzhou_4_4__gaussian_flows.json",
    "randomized/53__hangzhou_4_4__gaussian_flows.json",
    "randomized/54__hangzhou_4_4__gaussian_flows.json",
    "randomized/55__hangzhou_4_4__gaussian_flows.json",
    "randomized/56__hangzhou_4_4__gaussian_flows.json",
    "randomized/57__hangzhou_4_4__gaussian_flows.json",
    "randomized/58__hangzhou_4_4__gaussian_flows.json",
    "randomized/59__hangzhou_4_4__gaussian_flows.json",
    "randomized/60__hangzhou_4_4__gaussian_flows.json",
    "randomized/61__hangzhou_4_4__gaussian_flows.json",
    "randomized/62__hangzhou_4_4__gaussian_flows.json",
    "randomized/63__hangzhou_4_4__gaussian_flows.json",
    "randomized/64__hangzhou_4_4__gaussian_flows.json",
    "randomized/65__hangzhou_4_4__gaussian_flows.json",
    "randomized/66__hangzhou_4_4__gaussian_flows.json",
    "randomized/67__hangzhou_4_4__gaussian_flows.json",
    "randomized/68__hangzhou_4_4__gaussian_flows.json",
    "randomized/69__hangzhou_4_4__gaussian_flows.json",
    "randomized/70__hangzhou_4_4__gaussian_flows.json",
    "randomized/71__hangzhou_4_4__gaussian_flows.json",
    "randomized/72__hangzhou_4_4__gaussian_flows.json",
    "randomized/73__hangzhou_4_4__gaussian_flows.json",
    "randomized/74__hangzhou_4_4__gaussian_flows.json",
    "randomized/75__hangzhou_4_4__gaussian_flows.json",
    "randomized/76__hangzhou_4_4__gaussian_flows.json",
    "randomized/77__hangzhou_4_4__gaussian_flows.json",
    "randomized/78__hangzhou_4_4__gaussian_flows.json",
    "randomized/79__hangzhou_4_4__gaussian_flows.json",
    "randomized/80__hangzhou_4_4__gaussian_flows.json",
    "randomized/81__hangzhou_4_4__gaussian_flows.json",
    "randomized/82__hangzhou_4_4__gaussian_flows.json",
    "randomized/83__hangzhou_4_4__gaussian_flows.json",
    "randomized/84__hangzhou_4_4__gaussian_flows.json",
    "randomized/85__hangzhou_4_4__gaussian_flows.json",
    "randomized/86__hangzhou_4_4__gaussian_flows.json",
    "randomized/87__hangzhou_4_4__gaussian_flows.json",
    "randomized/88__hangzhou_4_4__gaussian_flows.json",
    "randomized/89__hangzhou_4_4__gaussian_flows.json",
    "randomized/90__hangzhou_4_4__gaussian_flows.json",
    "randomized/91__hangzhou_4_4__gaussian_flows.json",
    "randomized/92__hangzhou_4_4__gaussian_flows.json",
    "randomized/93__hangzhou_4_4__gaussian_flows.json",
    "randomized/94__hangzhou_4_4__gaussian_flows.json",
    "randomized/95__hangzhou_4_4__gaussian_flows.json",
    "randomized/96__hangzhou_4_4__gaussian_flows.json",
    "randomized/97__hangzhou_4_4__gaussian_flows.json",
    "randomized/98__hangzhou_4_4__gaussian_flows.json",
    "randomized/99__hangzhou_4_4__gaussian_flows.json",
  ]

signal:
  action_space: phase_selection
  round_robin: False
  reward_function: queue_length