cityflow:
  seed: 42
  thread_num: 4
  interval: 1.0
  rl_traffic_light: True
  plan: [5, 30, 30, 30, 30, 30, 30, 30, 30]
  lane_change: False
  delta_time: 5  # simulation steps between consecutive agent actions
  episode_limit: 360  # simulation seconds  n_steps = episode_limit / delta_time
  initial_wait_time: 0  # sim seconds to wait to populate the network
  veh_size_min_gap: 7  # vehicle_size + minimum gap or headway = 5 + 2
  roadnet_file: roadnet_2X2.json
  flow_file: syn_2x2_gaussian_500_1h.json
  save_replay: False
  roadnet_log_file: "frontend/web/roadnet_log_file.json"
  replay_log_file: "frontend/web/replay_log_file.txt"


# network:
#   neighbors:
#     "intersection_1_1": ["intersection_1_2", "intersection_2_1"]
#     "intersection_1_2": ["intersection_1_1", "intersection_2_2"]
#     "intersection_2_1": ["intersection_1_1", "intersection_2_2"]
#     "intersection_2_2": ["intersection_1_2", "intersection_2_1"]
#   neighbors_lanes:
#     "intersection_1_1":
#       "intersection_1_2": ["road_1_1_1_0", "road_1_1_1_1"]
#       "intersection_2_1": ["road_1_1_0_0", "road_1_1_0_1"]
#     "intersection_1_2":
#       "intersection_1_1": ["road_1_2_3_0", "road_1_2_3_1"]
#       "intersection_2_2": ["road_2_2_2_0", "road_2_2_2_1"]
#     "intersection_2_1":
#       "intersection_1_1": ["road_2_1_2_0", "road_2_1_2_1"]
#       "intersection_2_2": ["road_2_1_1_0", "road_2_1_1_1"]
#     "intersection_2_2":
#       "intersection_1_2": ["road_2_2_2_0", "road_2_2_2_1"]
#       "intersection_2_1": ["road_2_2_3_0", "road_2_2_3_1"]
