# https://github.com/Pi-Star-Lab/RESCO/tree/main
# SUMO parameters
sumo:
  render: False
  sumo_config_file: ingolstadt21.sumocfg
  sumo_net_file: ingolstadt21.net.xml

# Network parameters
network:
  network_type: real # (synthetic, real)