cityflow:
  plan: [5, 30, 30, 30, 30, 30, 30, 30, 30]
  # phase_sequence: [1, 0, 3, 0, 2, 0, 4, 0]  # 0 is a common yellow phase
  roadnet_file: 1x1_roadnet.json
  flow_file: syn_1x1__gaussian_600_flows.json
  flow_files: [
    "syn_1x1__gaussian_100_flows.json",
    "syn_1x1__gaussian_125_flows.json",
    "syn_1x1__gaussian_150_flows.json",
    "syn_1x1__gaussian_175_flows.json",
    "syn_1x1__gaussian_200_flows.json",
    "syn_1x1__gaussian_225_flows.json",
    "syn_1x1__gaussian_250_flows.json",
    "syn_1x1__gaussian_275_flows.json",
    "syn_1x1__gaussian_300_flows.json",
    "syn_1x1__gaussian_325_flows.json",
    "syn_1x1__gaussian_350_flows.json",
    "syn_1x1__gaussian_375_flows.json",
    "syn_1x1__gaussian_400_flows.json",
    "syn_1x1__gaussian_425_flows.json",
    "syn_1x1__gaussian_450_flows.json",
    "syn_1x1__gaussian_475_flows.json",
    "syn_1x1__gaussian_500_flows.json",
    "syn_1x1__gaussian_525_flows.json",
    "syn_1x1__gaussian_550_flows.json",
    "syn_1x1__gaussian_575_flows.json",
    "syn_1x1__gaussian_600_flows.json",
    "syn_1x1__gaussian_625_flows.json",
    "syn_1x1__gaussian_650_flows.json",
    "syn_1x1__gaussian_675_flows.json",
    "syn_1x1__gaussian_700_flows.json",
  ]
  roadnet_log_file: "roadnet_log_file.json"
  replay_log_file: "replay_log_file.txt"
  save_replay: False

signal:
  action_space: phase_selection
  round_robin: False
  reward_function: queue_length