# SUMO parameters
sumo:
  render: False
  # sumo_config_file: cologne_1.sumocfg
  sumo_net_file: random_subnetwork_1.net.xml
  random_game: True
  sumo_config_files:
    - random_subnetwork_1_light.sumocfg
    - random_subnetwork_1_medium.sumocfg
    - random_subnetwork_1_heavy.sumocfg

# Network parameters
network:
  network_type: real # (synthetic, real)