# SUMO parameters
sumo:
  render: False
  # sumo_config_file: cologne_1.sumocfg
  sumo_net_file: random_grid_7.net.xml
  random_game: True
  sumo_config_files:
    - random_grid_7_light.sumocfg
    - random_grid_7_medium.sumocfg
    - random_grid_7_heavy.sumocfg

# Network parameters
network:
  network_type: real # (synthetic, real)