cityflow:
  # plan: [5, 30, 30, 30, 30, 30, 30, 30, 30]
  # phase_sequence: [1, 0, 3, 0, 2, 0, 4, 0]  # 0 is a common yellow phase
  roadnet_file: roadnet.json
  flow_file: gaussian_500__flow.json
  flow_rate_type: 'constant'
  flow_files: []
  roadnet_log_file: "roadnet_log_file.json"
  replay_log_file: "replay_log_file.txt"
  save_replay: False

signal:
  action_space: phase_selection
  round_robin: False
  reward_function: queue_length
