cityflow:
  plan: [5, 30, 30, 30, 30, 30, 30, 30, 30]
  # phase_sequence: [1, 0, 3, 0, 2, 0, 4, 0]  # 0 is a common yellow phase
  roadnet_file: roadnet_16_3.json
  flow_file: anon_16_3_newyork_real.json
  roadnet_log_file: "frontend/web/roadnet_log_file.json"
  replay_log_file: "frontend/web/replay_log_file.txt"
  save_replay: False
  flow_rate_type: "random"
  flow_files: [
    "randomized/low/0__manhattan_16x3__gaussian_flows.json",
    "randomized/low/1__manhattan_16x3__gaussian_flows.json",
    "randomized/low/2__manhattan_16x3__gaussian_flows.json",
    "randomized/low/3__manhattan_16x3__gaussian_flows.json",
    "randomized/low/4__manhattan_16x3__gaussian_flows.json",
    "randomized/low/5__manhattan_16x3__gaussian_flows.json",
    "randomized/low/6__manhattan_16x3__gaussian_flows.json",
    "randomized/low/7__manhattan_16x3__gaussian_flows.json",
    "randomized/low/8__manhattan_16x3__gaussian_flows.json",
    "randomized/low/9__manhattan_16x3__gaussian_flows.json",
    "randomized/low/10__manhattan_16x3__gaussian_flows.json",
    "randomized/low/11__manhattan_16x3__gaussian_flows.json",
    "randomized/low/12__manhattan_16x3__gaussian_flows.json",
    "randomized/low/13__manhattan_16x3__gaussian_flows.json",
    "randomized/low/14__manhattan_16x3__gaussian_flows.json",
    "randomized/low/15__manhattan_16x3__gaussian_flows.json",
    "randomized/low/16__manhattan_16x3__gaussian_flows.json",
    "randomized/low/17__manhattan_16x3__gaussian_flows.json",
    "randomized/low/18__manhattan_16x3__gaussian_flows.json",
    "randomized/low/19__manhattan_16x3__gaussian_flows.json",
    "randomized/low/20__manhattan_16x3__gaussian_flows.json",
    "randomized/low/21__manhattan_16x3__gaussian_flows.json",
    "randomized/low/22__manhattan_16x3__gaussian_flows.json",
    "randomized/low/23__manhattan_16x3__gaussian_flows.json",
    "randomized/low/24__manhattan_16x3__gaussian_flows.json",
    "randomized/low/25__manhattan_16x3__gaussian_flows.json",
    "randomized/low/26__manhattan_16x3__gaussian_flows.json",
    "randomized/low/27__manhattan_16x3__gaussian_flows.json",
    "randomized/low/28__manhattan_16x3__gaussian_flows.json",
    "randomized/low/29__manhattan_16x3__gaussian_flows.json",
    "randomized/low/30__manhattan_16x3__gaussian_flows.json",
    "randomized/low/31__manhattan_16x3__gaussian_flows.json",
    "randomized/low/32__manhattan_16x3__gaussian_flows.json",
    "randomized/low/33__manhattan_16x3__gaussian_flows.json",
    "randomized/low/34__manhattan_16x3__gaussian_flows.json",
    "randomized/low/35__manhattan_16x3__gaussian_flows.json",
    "randomized/low/36__manhattan_16x3__gaussian_flows.json",
    "randomized/low/37__manhattan_16x3__gaussian_flows.json",
    "randomized/low/38__manhattan_16x3__gaussian_flows.json",
    "randomized/low/39__manhattan_16x3__gaussian_flows.json",
    "randomized/low/40__manhattan_16x3__gaussian_flows.json",
    "randomized/low/41__manhattan_16x3__gaussian_flows.json",
    "randomized/low/42__manhattan_16x3__gaussian_flows.json",
    "randomized/low/43__manhattan_16x3__gaussian_flows.json",
    "randomized/low/44__manhattan_16x3__gaussian_flows.json",
    "randomized/low/45__manhattan_16x3__gaussian_flows.json",
    "randomized/low/46__manhattan_16x3__gaussian_flows.json",
    "randomized/low/47__manhattan_16x3__gaussian_flows.json",
    "randomized/low/48__manhattan_16x3__gaussian_flows.json",
    "randomized/low/49__manhattan_16x3__gaussian_flows.json",
    "randomized/low/50__manhattan_16x3__gaussian_flows.json",
    "randomized/low/51__manhattan_16x3__gaussian_flows.json",
    "randomized/low/52__manhattan_16x3__gaussian_flows.json",
    "randomized/low/53__manhattan_16x3__gaussian_flows.json",
    "randomized/low/54__manhattan_16x3__gaussian_flows.json",
    "randomized/low/55__manhattan_16x3__gaussian_flows.json",
    "randomized/low/56__manhattan_16x3__gaussian_flows.json",
    "randomized/low/57__manhattan_16x3__gaussian_flows.json",
    "randomized/low/58__manhattan_16x3__gaussian_flows.json",
    "randomized/low/59__manhattan_16x3__gaussian_flows.json",
    "randomized/low/60__manhattan_16x3__gaussian_flows.json",
    "randomized/low/61__manhattan_16x3__gaussian_flows.json",
    "randomized/low/62__manhattan_16x3__gaussian_flows.json",
    "randomized/low/63__manhattan_16x3__gaussian_flows.json",
    "randomized/low/64__manhattan_16x3__gaussian_flows.json",
    "randomized/low/65__manhattan_16x3__gaussian_flows.json",
    "randomized/low/66__manhattan_16x3__gaussian_flows.json",
    "randomized/low/67__manhattan_16x3__gaussian_flows.json",
    "randomized/low/68__manhattan_16x3__gaussian_flows.json",
    "randomized/low/69__manhattan_16x3__gaussian_flows.json",
    "randomized/low/70__manhattan_16x3__gaussian_flows.json",
    "randomized/low/71__manhattan_16x3__gaussian_flows.json",
    "randomized/low/72__manhattan_16x3__gaussian_flows.json",
    "randomized/low/73__manhattan_16x3__gaussian_flows.json",
    "randomized/low/74__manhattan_16x3__gaussian_flows.json",
    "randomized/low/75__manhattan_16x3__gaussian_flows.json",
    "randomized/low/76__manhattan_16x3__gaussian_flows.json",
    "randomized/low/77__manhattan_16x3__gaussian_flows.json",
    "randomized/low/78__manhattan_16x3__gaussian_flows.json",
    "randomized/low/79__manhattan_16x3__gaussian_flows.json",
    "randomized/low/80__manhattan_16x3__gaussian_flows.json",
    "randomized/low/81__manhattan_16x3__gaussian_flows.json",
    "randomized/low/82__manhattan_16x3__gaussian_flows.json",
    "randomized/low/83__manhattan_16x3__gaussian_flows.json",
    "randomized/low/84__manhattan_16x3__gaussian_flows.json",
    "randomized/low/85__manhattan_16x3__gaussian_flows.json",
    "randomized/low/86__manhattan_16x3__gaussian_flows.json",
    "randomized/low/87__manhattan_16x3__gaussian_flows.json",
    "randomized/low/88__manhattan_16x3__gaussian_flows.json",
    "randomized/low/89__manhattan_16x3__gaussian_flows.json",
    "randomized/low/90__manhattan_16x3__gaussian_flows.json",
    "randomized/low/91__manhattan_16x3__gaussian_flows.json",
    "randomized/low/92__manhattan_16x3__gaussian_flows.json",
    "randomized/low/93__manhattan_16x3__gaussian_flows.json",
    "randomized/low/94__manhattan_16x3__gaussian_flows.json",
    "randomized/low/95__manhattan_16x3__gaussian_flows.json",
    "randomized/low/96__manhattan_16x3__gaussian_flows.json",
    "randomized/low/97__manhattan_16x3__gaussian_flows.json",
    "randomized/low/98__manhattan_16x3__gaussian_flows.json",
    "randomized/low/99__manhattan_16x3__gaussian_flows.json",
  ]

signal:
  action_space: phase_selection
  round_robin: False
  reward_function: queue_length