# SUMO parameters
sumo:
  render: False
  sumo_config_file: 2x2_sumo_grid.sumocfg
  sumo_net_file: 2x2_sumo_grid.net.xml

# Network parameters
network:
  network_type: synthetic # (synthetic, real)

signal:
  yellow_time: 5
  min_green_time: 5
  max_green_time: 60
  visibility: 10  # range of visibility in n_bins
  round_robin: True  # if True, the signal cycles through the phases in order

grid_generator:
  grid_length: 300
  grid_x_number: 2
  grid_y_number: 2
  grid_attach_length: 300
  add_turn_lane: True