cityflow:
  # phase_sequence: [1, 0, 3, 0, 2, 0, 4, 0]  # 0 is a common yellow phase
  roadnet_file: syn_1x7_roadnet.json
  flow_file: syn_1x7__gaussian_396_flows.json
  roadnet_log_file: "roadnet_log_file.json"
  replay_log_file: "replay_log_file.txt"
  save_replay: False

signal:
  action_space: phase_selection
  round_robin: False
  reward_function: queue_length