cityflow:
  plan: [25, 5, 25, 5]
  roadnet_file: 1x2_roadnet.json
  flow_rate_type: "constant"
  flow_file: 1x2_roadnet_600.json
  roadnet_log_file: "roadnet_log_file.json"
  replay_log_file: "replay_log_file.txt"
  save_replay: False
  sim_length: 360

signal:
  action_space: "phase_selection"
  round_robin: True
