# SUMO parameters
sumo:
  render: False
  random_game: False
  sumo_config_file: single.sumocfg
  sumo_net_file: single.net.xml
  sumo_config_files: [
    "single.sumocfg",
    "single_left.sumocfg",
    "single_right.sumocfg",
    "single_top.sumocfg",
    "single_bottom.sumocfg",
  ]
  sumo_net_files: [
    "single.net.xml",
    "single_left.net.xml",
    "single_right.net.xml",
    "single_top.net.xml",
    "single_bottom.net.xml",
  ]

# Network parameters
network:
  network_type: synthetic # (synthetic, real)

signal:
  yellow_time: 5
  min_green_time: 5
  max_green_time: 25
  visibility: 10  # range of visibility in n_bins
  round_robin: True  # if True, the signal cycles through the phases in order
