cityflow:
  plan: [5, 30, 30, 30, 30, 30, 30, 30, 30]
  # phase_sequence: [1, 0, 3, 0, 2, 0, 4, 0]  # 0 is a common yellow phase
  roadnet_file: 3x3_roadnet.json
  flow_file: syn_3x3__gaussian_flow_rate_600_flows.json
  flow_files: [
    "syn_3x3__gaussian_500_flows.json",
    "syn_3x3__gaussian_525_flows.json",
    "syn_3x3__gaussian_550_flows.json",
    "syn_3x3__gaussian_575_flows.json",
    "syn_3x3__gaussian_600_flows.json",
    "syn_3x3__gaussian_625_flows.json",
    "syn_3x3__gaussian_650_flows.json",
    "syn_3x3__gaussian_675_flows.json",
    "syn_3x3__gaussian_700_flows.json",
  ]
  roadnet_log_file: "roadnet_log_file.json"
  replay_log_file: "replay_log_file.txt"
  save_replay: False

signal:
  action_space: phase_selection
  round_robin: False
  reward_function: max_pressure