cityflow:
  seed: 42
  thread_num: 1
  interval: 1.0
  rl_traffic_light: True
  plan: [5, 30, 30, 30, 30, 30, 30, 30, 30]
  lane_change: False
  delta_time: 5  # simulation steps between consecutive agent actions
  episode_limit: 60  # simulation seconds  n_steps = episode_limit / delta_time
  initial_wait_time: 0  # sim seconds to wait to populate the network
  veh_size_min_gap: 7.5  # vehicle_size + minimum gap or headway = 5 + 2.5
  roadnet_file: roadnet_28_7.json
  flow_file: anon_28_7_newyork_real_double.json
  save_replay: False
  roadnet_log_file: "frontend/web/roadnet_log_file.json"
  replay_log_file: "frontend/web/replay_log_file.txt"

