cityflow:
  plan: [5, 30, 30, 30, 30, 30, 30, 30, 30]
  phase_sequence: [1, 0, 3, 0, 2, 0, 4, 0]  # 0 is a common yellow phase
  roadnet_file: roadnet_28_7.json
  flow_file: anon_28_7_newyork_real_double.json
  roadnet_log_file: "frontend/web/roadnet_log_file.json"
  replay_log_file: "frontend/web/replay_log_file.txt"
  save_replay: False

signal:
  action_space: phase_selection
  round_robin: False
  reward_function: max_pressure