# SUMO parameters
sumo:
  sumo_net_file: random_grid.net.xml
  sumo_config_file: random_grid_0.4_increased_demand.sumocfg
  random_game: False

# Network parameters
network:
  network_type: synthetic # (synthetic, real)
