cityflow:
  plan: [25, 5, 25, 5]
  roadnet_file: 1x2_roadnet.json
  flow_rate_type: "random"
  flow_files: [
    "train/1x2_roadnet_600_burst_1_15_2_29.json",
    "train/1x2_roadnet_600_burst_1_15_2_38.json",
    "train/1x2_roadnet_600_burst_1_15_2_43.json",
    "train/1x2_roadnet_600_burst_1_15_2_48.json",
    "train/1x2_roadnet_600_burst_1_15_2_50.json",
    "train/1x2_roadnet_600_burst_1_15_2_60.json",
    "train/1x2_roadnet_600_burst_1_15_2_61.json",
    "train/1x2_roadnet_600_burst_1_15_2_69.json",
    "train/1x2_roadnet_600_burst_1_15_2_73.json",
    "train/1x2_roadnet_600_burst_1_15_2_74.json",
    "train/1x2_roadnet_600_burst_1_15_2_75.json",
    "train/1x2_roadnet_600_burst_1_15_2_83.json",
    "train/1x2_roadnet_600_burst_1_15_2_84.json",
    "train/1x2_roadnet_600_burst_1_15_2_85.json",
    "train/1x2_roadnet_600_burst_1_15_2_86.json",
  ]
  roadnet_log_file: "roadnet_log_file.json"
  replay_log_file: "replay_log_file.txt"
  save_replay: False
  sim_length: 360

signal:
  action_space: "phase_selection"
  round_robin: True
