cityflow:
  plan: [5, 30, 30, 30, 30, 30, 30, 30, 30]
  # phase_sequence: [1, 0, 3, 0, 2, 0, 4, 0]  # 0 is a common yellow phase
  roadnet_file: 2x2_roadnet.json
  flow_file: 1__syn_2x2__interval_700_flows.json
  flow_files: [
    "1__syn_2x2__interval_700_flows.json",
    "2__syn_2x2__interval_700_flows.json",
    "3__syn_2x2__interval_700_flows.json",
    "4__syn_2x2__interval_700_flows.json",
    "5__syn_2x2__interval_700_flows.json",
  ]
  roadnet_log_file: "frontend/web/roadnet_log_file.json"
  replay_log_file: "frontend/web/replay_log_file.txt"
  save_replay: True

signal:
  action_space: phase_selection
  round_robin: False
  reward_function: queue_length