cityflow:
  plan: [5, 30, 30, 30, 30, 30, 30, 30, 30]
  # phase_sequence: [1, 0, 3, 0, 2, 0, 4, 0]  # 0 is a common yellow phase
  roadnet_file: roadnet_28_7.json
  flow_file: anon_28_7_newyork_real_double.json
  roadnet_log_file: "frontend/web/roadnet_log_file.json"
  replay_log_file: "frontend/web/replay_log_file.txt"
  save_replay: False
  flow_rate_type: "random"
  flow_classes: ['flow_disrupted', 'link_disrupted']
  train:
    link_disrupted:
      '0_1': [
        '0__manhattan_28_7__dr_0.1__gaussian_700_flows.json',
        '1__manhattan_28_7__dr_0.1__gaussian_700_flows.json',
        '2__manhattan_28_7__dr_0.1__gaussian_700_flows.json',
        '3__manhattan_28_7__dr_0.1__gaussian_700_flows.json',
        '4__manhattan_28_7__dr_0.1__gaussian_700_flows.json',
        '5__manhattan_28_7__dr_0.1__gaussian_700_flows.json',
        '6__manhattan_28_7__dr_0.1__gaussian_700_flows.json',
        '7__manhattan_28_7__dr_0.1__gaussian_700_flows.json',
        '8__manhattan_28_7__dr_0.1__gaussian_700_flows.json',
        '9__manhattan_28_7__dr_0.1__gaussian_700_flows.json',
      ]
      '0_3': [
        '0__manhattan_28_7__dr_0.3__gaussian_700_flows.json',
        '1__manhattan_28_7__dr_0.3__gaussian_700_flows.json',
        '2__manhattan_28_7__dr_0.3__gaussian_700_flows.json',
        '3__manhattan_28_7__dr_0.3__gaussian_700_flows.json',
        '4__manhattan_28_7__dr_0.3__gaussian_700_flows.json',
        '5__manhattan_28_7__dr_0.3__gaussian_700_flows.json',
        '6__manhattan_28_7__dr_0.3__gaussian_700_flows.json',
        '7__manhattan_28_7__dr_0.3__gaussian_700_flows.json',
        '8__manhattan_28_7__dr_0.3__gaussian_700_flows.json',
        '9__manhattan_28_7__dr_0.3__gaussian_700_flows.json',
      ]
    flow_disrupted:
      # '600': [
      #   '0__manhattan_28_7__gaussian_600_flows.json',
      #   '1__manhattan_28_7__gaussian_600_flows.json',
      #   '2__manhattan_28_7__gaussian_600_flows.json',
      #   '3__manhattan_28_7__gaussian_600_flows.json',
      #   '4__manhattan_28_7__gaussian_600_flows.json',
      #   '5__manhattan_28_7__gaussian_600_flows.json',
      #   '6__manhattan_28_7__gaussian_600_flows.json',
      #   '7__manhattan_28_7__gaussian_600_flows.json',
      #   '8__manhattan_28_7__gaussian_600_flows.json',
      #   '9__manhattan_28_7__gaussian_600_flows.json',
      # ]
      # '700': [
      #   '0__manhattan_28_7__gaussian_700_flows.json',
      #   '1__manhattan_28_7__gaussian_700_flows.json',
      #   '2__manhattan_28_7__gaussian_700_flows.json',
      #   '3__manhattan_28_7__gaussian_700_flows.json',
      #   '4__manhattan_28_7__gaussian_700_flows.json',
      #   '5__manhattan_28_7__gaussian_700_flows.json',
      #   '6__manhattan_28_7__gaussian_700_flows.json',
      #   '7__manhattan_28_7__gaussian_700_flows.json',
      #   '8__manhattan_28_7__gaussian_700_flows.json',
      #   '9__manhattan_28_7__gaussian_700_flows.json',
      # ]
      # '750': [
      #   '0__manhattan_28_7__gaussian_750_flows.json',
      #   '1__manhattan_28_7__gaussian_750_flows.json',
      #   '2__manhattan_28_7__gaussian_750_flows.json',
      #   '3__manhattan_28_7__gaussian_750_flows.json',
      #   '4__manhattan_28_7__gaussian_750_flows.json',
      #   '5__manhattan_28_7__gaussian_750_flows.json',
      #   '6__manhattan_28_7__gaussian_750_flows.json',
      #   '7__manhattan_28_7__gaussian_750_flows.json',
      #   '8__manhattan_28_7__gaussian_750_flows.json',
      #   '9__manhattan_28_7__gaussian_750_flows.json',
      # ]
      # '800': [
      #   '0__manhattan_28_7__gaussian_800_flows.json',
      #   '1__manhattan_28_7__gaussian_800_flows.json',
      #   '2__manhattan_28_7__gaussian_800_flows.json',
      #   '3__manhattan_28_7__gaussian_800_flows.json',
      #   '4__manhattan_28_7__gaussian_800_flows.json',
      #   '5__manhattan_28_7__gaussian_800_flows.json',
      #   '6__manhattan_28_7__gaussian_800_flows.json',
      #   '7__manhattan_28_7__gaussian_800_flows.json',
      #   '8__manhattan_28_7__gaussian_800_flows.json',
      #   '9__manhattan_28_7__gaussian_800_flows.json',
      # ]
      "0_1": [
        "0__manhattan_28_7__fd_0.1__gaussian_700_flows.json",
        "1__manhattan_28_7__fd_0.1__gaussian_700_flows.json",
        "2__manhattan_28_7__fd_0.1__gaussian_700_flows.json",
        "3__manhattan_28_7__fd_0.1__gaussian_700_flows.json",
        "4__manhattan_28_7__fd_0.1__gaussian_700_flows.json",
        "5__manhattan_28_7__fd_0.1__gaussian_700_flows.json",
        "6__manhattan_28_7__fd_0.1__gaussian_700_flows.json",
        "7__manhattan_28_7__fd_0.1__gaussian_700_flows.json",
        "8__manhattan_28_7__fd_0.1__gaussian_700_flows.json",
        "9__manhattan_28_7__fd_0.1__gaussian_700_flows.json",
      ]
      "0_2": [
        "0__manhattan_28_7__fd_0.2__gaussian_700_flows.json",
        "1__manhattan_28_7__fd_0.2__gaussian_700_flows.json",
        "2__manhattan_28_7__fd_0.2__gaussian_700_flows.json",
        "3__manhattan_28_7__fd_0.2__gaussian_700_flows.json",
        "4__manhattan_28_7__fd_0.2__gaussian_700_flows.json",
        "5__manhattan_28_7__fd_0.2__gaussian_700_flows.json",
        "6__manhattan_28_7__fd_0.2__gaussian_700_flows.json",
        "7__manhattan_28_7__fd_0.2__gaussian_700_flows.json",
        "8__manhattan_28_7__fd_0.2__gaussian_700_flows.json",
        "9__manhattan_28_7__fd_0.2__gaussian_700_flows.json",
      ]
      "0_5": [
        "0__manhattan_28_7__fd_0.5__gaussian_700_flows.json",
        "1__manhattan_28_7__fd_0.5__gaussian_700_flows.json",
        "2__manhattan_28_7__fd_0.5__gaussian_700_flows.json",
        "3__manhattan_28_7__fd_0.5__gaussian_700_flows.json",
        "4__manhattan_28_7__fd_0.5__gaussian_700_flows.json",
        "5__manhattan_28_7__fd_0.5__gaussian_700_flows.json",
        "6__manhattan_28_7__fd_0.5__gaussian_700_flows.json",
        "7__manhattan_28_7__fd_0.5__gaussian_700_flows.json",
        "8__manhattan_28_7__fd_0.5__gaussian_700_flows.json",
        "9__manhattan_28_7__fd_0.5__gaussian_700_flows.json",
      ]
      "0_6": [
        "0__manhattan_28_7__fd_0.6__gaussian_700_flows.json",
        "1__manhattan_28_7__fd_0.6__gaussian_700_flows.json",
        "2__manhattan_28_7__fd_0.6__gaussian_700_flows.json",
        "3__manhattan_28_7__fd_0.6__gaussian_700_flows.json",
        "4__manhattan_28_7__fd_0.6__gaussian_700_flows.json",
        "5__manhattan_28_7__fd_0.6__gaussian_700_flows.json",
        "6__manhattan_28_7__fd_0.6__gaussian_700_flows.json",
        "7__manhattan_28_7__fd_0.6__gaussian_700_flows.json",
        "8__manhattan_28_7__fd_0.6__gaussian_700_flows.json",
        "9__manhattan_28_7__fd_0.6__gaussian_700_flows.json",
      ]
  test: 
    link_disrupted: 
      '0_2': [
        '0__manhattan_28_7__dr_0.2__gaussian_700_flows.json',
        '1__manhattan_28_7__dr_0.2__gaussian_700_flows.json',
        '2__manhattan_28_7__dr_0.2__gaussian_700_flows.json',
        '3__manhattan_28_7__dr_0.2__gaussian_700_flows.json',
        '4__manhattan_28_7__dr_0.2__gaussian_700_flows.json',
        '5__manhattan_28_7__dr_0.2__gaussian_700_flows.json',
        '6__manhattan_28_7__dr_0.2__gaussian_700_flows.json',
        '7__manhattan_28_7__dr_0.2__gaussian_700_flows.json',
        '8__manhattan_28_7__dr_0.2__gaussian_700_flows.json',
        '9__manhattan_28_7__dr_0.2__gaussian_700_flows.json',
      ]
      '0_4': [
        '0__manhattan_28_7__dr_0.4__gaussian_700_flows.json',
        '1__manhattan_28_7__dr_0.4__gaussian_700_flows.json',
        '2__manhattan_28_7__dr_0.4__gaussian_700_flows.json',
        '3__manhattan_28_7__dr_0.4__gaussian_700_flows.json',
        '4__manhattan_28_7__dr_0.4__gaussian_700_flows.json',
        '5__manhattan_28_7__dr_0.4__gaussian_700_flows.json',
        '6__manhattan_28_7__dr_0.4__gaussian_700_flows.json',
        '7__manhattan_28_7__dr_0.4__gaussian_700_flows.json',
        '8__manhattan_28_7__dr_0.4__gaussian_700_flows.json',
        '9__manhattan_28_7__dr_0.4__gaussian_700_flows.json',
      ]
    flow_disrupted: 
      # '650': [
      #   '0__manhattan_28_7__gaussian_650_flows.json',
      #   '1__manhattan_28_7__gaussian_650_flows.json',
      #   '2__manhattan_28_7__gaussian_650_flows.json',
      #   '3__manhattan_28_7__gaussian_650_flows.json',
      #   '4__manhattan_28_7__gaussian_650_flows.json',
      #   '5__manhattan_28_7__gaussian_650_flows.json',
      #   '6__manhattan_28_7__gaussian_650_flows.json',
      #   '7__manhattan_28_7__gaussian_650_flows.json',
      #   '8__manhattan_28_7__gaussian_650_flows.json',
      #   '9__manhattan_28_7__gaussian_650_flows.json',
      # ]
      # '850': [
      #   '0__manhattan_28_7__gaussian_850_flows.json',
      #   '1__manhattan_28_7__gaussian_850_flows.json',
      #   '2__manhattan_28_7__gaussian_850_flows.json',
      #   '3__manhattan_28_7__gaussian_850_flows.json',
      #   '4__manhattan_28_7__gaussian_850_flows.json',
      #   '5__manhattan_28_7__gaussian_850_flows.json',
      #   '6__manhattan_28_7__gaussian_850_flows.json',
      #   '7__manhattan_28_7__gaussian_850_flows.json',
      #   '8__manhattan_28_7__gaussian_850_flows.json',
      #   '9__manhattan_28_7__gaussian_850_flows.json',
      # ]
      # '900': [
      #   '0__manhattan_28_7__gaussian_900_flows.json',
      #   '1__manhattan_28_7__gaussian_900_flows.json',
      #   '2__manhattan_28_7__gaussian_900_flows.json',
      #   '3__manhattan_28_7__gaussian_900_flows.json',
      #   '4__manhattan_28_7__gaussian_900_flows.json',
      #   '5__manhattan_28_7__gaussian_900_flows.json',
      #   '6__manhattan_28_7__gaussian_900_flows.json',
      #   '7__manhattan_28_7__gaussian_900_flows.json',
      #   '8__manhattan_28_7__gaussian_900_flows.json',
      #   '9__manhattan_28_7__gaussian_900_flows.json',
      # ]
      "0_3": [
        "0__manhattan_28_7__fd_0.3__gaussian_700_flows.json",
        "1__manhattan_28_7__fd_0.3__gaussian_700_flows.json",
        "2__manhattan_28_7__fd_0.3__gaussian_700_flows.json",
        "3__manhattan_28_7__fd_0.3__gaussian_700_flows.json",
        "4__manhattan_28_7__fd_0.3__gaussian_700_flows.json",
        "5__manhattan_28_7__fd_0.3__gaussian_700_flows.json",
        "6__manhattan_28_7__fd_0.3__gaussian_700_flows.json",
        "7__manhattan_28_7__fd_0.3__gaussian_700_flows.json",
        "8__manhattan_28_7__fd_0.3__gaussian_700_flows.json",
        "9__manhattan_28_7__fd_0.3__gaussian_700_flows.json",
      ]
      "0_4": [
        "0__manhattan_28_7__fd_0.4__gaussian_700_flows.json",
        "1__manhattan_28_7__fd_0.4__gaussian_700_flows.json",
        "2__manhattan_28_7__fd_0.4__gaussian_700_flows.json",
        "3__manhattan_28_7__fd_0.4__gaussian_700_flows.json",
        "4__manhattan_28_7__fd_0.4__gaussian_700_flows.json",
        "5__manhattan_28_7__fd_0.4__gaussian_700_flows.json",
        "6__manhattan_28_7__fd_0.4__gaussian_700_flows.json",
        "7__manhattan_28_7__fd_0.4__gaussian_700_flows.json",
        "8__manhattan_28_7__fd_0.4__gaussian_700_flows.json",
        "9__manhattan_28_7__fd_0.4__gaussian_700_flows.json",
      ]
      "0_7": [
        "0__manhattan_28_7__fd_0.7__gaussian_700_flows.json",
        "1__manhattan_28_7__fd_0.7__gaussian_700_flows.json",
        "2__manhattan_28_7__fd_0.7__gaussian_700_flows.json",
        "3__manhattan_28_7__fd_0.7__gaussian_700_flows.json",
        "4__manhattan_28_7__fd_0.7__gaussian_700_flows.json",
        "5__manhattan_28_7__fd_0.7__gaussian_700_flows.json",
        "6__manhattan_28_7__fd_0.7__gaussian_700_flows.json",
        "7__manhattan_28_7__fd_0.7__gaussian_700_flows.json",
        "8__manhattan_28_7__fd_0.7__gaussian_700_flows.json",
        "9__manhattan_28_7__fd_0.7__gaussian_700_flows.json",
      ]

signal:
  action_space: phase_selection
  round_robin: False
  reward_function: queue_length