cityflow:
  plan: [5, 30, 30, 30, 30, 30, 30, 30, 30]
  # phase_sequence: [1, 0, 3, 0, 2, 0, 4, 0]  # 0 is a common yellow phase
  roadnet_file: roadnet_28_7.json
  flow_file: anon_28_7_newyork_real_double.json
  roadnet_log_file: "frontend/web/roadnet_log_file.json"
  replay_log_file: "frontend/web/replay_log_file.txt"
  save_replay: False
  flow_rate_type: "random"
  flow_files: [
    "randomized/medium/0__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/1__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/2__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/3__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/4__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/5__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/6__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/7__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/8__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/9__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/10__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/11__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/12__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/13__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/14__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/15__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/16__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/17__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/18__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/19__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/20__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/21__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/22__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/23__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/24__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/25__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/26__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/27__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/28__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/29__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/30__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/31__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/32__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/33__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/34__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/35__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/36__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/37__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/38__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/39__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/40__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/41__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/42__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/43__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/44__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/45__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/46__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/47__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/48__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/49__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/50__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/51__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/52__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/53__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/54__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/55__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/56__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/57__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/58__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/59__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/60__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/61__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/62__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/63__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/64__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/65__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/66__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/67__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/68__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/69__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/70__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/71__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/72__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/73__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/74__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/75__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/76__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/77__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/78__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/79__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/80__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/81__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/82__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/83__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/84__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/85__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/86__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/87__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/88__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/89__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/90__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/91__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/92__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/93__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/94__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/95__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/96__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/97__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/98__manhattan_28_7__gaussian_flows.json",
    "randomized/medium/99__manhattan_28_7__gaussian_flows.json",
  ]

signal:
  action_space: phase_selection
  round_robin: False
  reward_function: queue_length